name: CI/CD for Cardio API V1

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest test.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin 098578355748.dkr.ecr.us-east-1.amazonaws.com

      - name: Build, tag, and push Docker image
        run: |
          docker build --platform=linux/amd64 -t cardio-api:v1 .
          docker tag cardio-api:v1 098578355748.dkr.ecr.us-east-1.amazonaws.com/cardio-api1:v1
          docker push 098578355748.dkr.ecr.us-east-1.amazonaws.com/cardio-api1:v1

      - name: SSH into EC2 and deploy container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if docker ps -a --format '{{.Names}}' | grep -Eq "^cardio-api$"; then
              docker stop cardio-api
              docker rm cardio-api
            fi
            docker pull 098578355748.dkr.ecr.us-east-1.amazonaws.com/cardio-api1:v1
            docker run -d -p 8000:8000 --name cardio-api 098578355748.dkr.ecr.us-east-1.amazonaws.com/cardio-api1:v1
